auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: lvzhonghou.com
url: http://lvzhonghou.com
feed: /atom.xml
author_info: <a href="http://lvzhonghou.com/">lvzhonghou</a>
